language: node_js
node_js:
  - 12
cache: yarn
install: yarn
before_script:
  - "yarn test && yarn testcafe"
script:
  - "yarn build"
after_success:
  - "serve -s build"
  - "yarn testcafe:built"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: build
  target-branch: master
  on:
    branch: source
notifications:
  webhooks:
    urls: https://fathomless-fjord-24024.herokuapp.com/notify
    on_success: change
