language: node_js
cache: yarn
install: yarn
before_script:
  - "yarn test"
  - "yarn testcafe"
script:
  - "yarn build"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
